apiVersion: apps/v1
kind: Deployment
metadata:
  name: db # Name of the Deployment resource
  labels:
    app: db # Label used to identify the Deployment
spec:
  selector:          
    matchLabels:     
      app: db # Selector to match pods with this label
  replicas: 1 # Number of replicas for this pod
  template:
    metadata:
      labels:
        app: db # Label assigned to each pod managed by this Deployment
    spec:
      containers:
      - name: db # Name of the main database container
        image: itsnotrohit/webapp-mysql # Container image for the MySQL database

        ports:
        - name: db-port # Identifier for the database port
          containerPort: 3306 # MySQL default port for accepting connections

        env:
         - name: MYSQL_ROOT_PASSWORD # Environment variable for the MySQL root password
           valueFrom:
             secretKeyRef:
               name: project-secrets # References the Kubernetes Secret containing sensitive data
               key: db-password # The specific key within the secret for the root password
